### ISSUE TITLE
Implementation of Presolve

### ISSUE THREAD

**Issue by Vandermode** [leavesgrp/ABIP#1]
Hi~ Thank you for the nice work!

I was wondering if you could let me know where is the implementation of Presolve described in Section 4.5 [1]
I searched the keyword "presolve" in this codebase but cannot find one match.

[1] An ADMM-based interior-point method for large-scale linear programming

**Comment by Gwzwpxz** [comment]
Hello, sorry for the delayed reply.

The initial version of ABIP [1] implemented a presolve/postsolve procedure in MATLAB and the
 solver itself has no internal presolving routine. We've attached the MATLAB [presolve/postsolve scripts](https://github.com/leavesgrp/ABIP/files/12564411/abip_pre_postsolve.zip) FYR.

Thanks for reaching out!
